language: c

os:
  - linux

compiler:
    - clang
    - gcc

before_script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libboost-all-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install automake autoconf boost; fi

script:
    - ./bootstrap
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./configure --enable-test; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./configure_macosx --enable-test; fi
    - make
    - make check

addons:
  homebrew:
    packages:
      - beanstalk
notifications:
  email: false
