#!/bin/bash

pushd include    && ./Makefile.am.build > Makefile.am && popd
pushd lib/unix   && ./Makefile.am.build > Makefile.am && popd
pushd test/unix && ./Makefile.am.build > Makefile.am && popd

rm -rf config autom4te.cache

if [ ! -d config ]; then
    mkdir config
fi
if [ ! -d autom4te.cache ]; then
	rm -rf autom4te.cache/*
fi
#libtoolize --automake --force --copy
aclocal
autoheader
automake --foreign --add-missing --copy
autoconf 
