#!/bin/bash
cd /Users/skonno/Src/mupnp/doc

DOCX_FILES=("mupnpcproguide.docx" "mupnpobjcproguide.docx")
PANDOC_PARAMS="-f docx -t markdown --wrap=none"

for DOC_FILE in "${DOCX_FILES[@]}"; do
    pandoc ${PANDOC_PARAMS} ${DOC_FILE} -o ${DOC_FILE%.docx}.md
    sed -i '' 's/^> //' ${DOC_FILE%.docx}.md
done