//
//  CGUpnpAvConstants.h
//  CyberLink for C
//
//  Created by Satoshi Konno on 08/07/10.
//  Copyright 2008 Satoshi Konno. All rights reserved.
//

/****************************************
* Constants (Media Server)
****************************************/

#define CG_UPNPAV_MEDIASERVER_DEVICE_TYPE @"urn:schemas-upnp-org:device:MediaServer:1"
#define CG_UPNPAV_DEFAULT_HTTP_PORT 38520

/****************************************
 * Constants (Media Renderer)
 ****************************************/

#define CG_UPNPAV_MEDIARENDERER_DEVICE_TYPE @"urn:schemas-upnp-org:device:MediaRenderer:1"

#define CG_UPNPAV_AVTRNSPORT_SERVICE_TYPE @"urn:schemas-upnp-org:service:AVTransport:1"

#define CG_UPNPAV_AVTRNSPORT_BROWSE @"SetAVTransportURI"
#define CG_UPNPAV_AVTRNSPORT_STOP @"Stop"
#define CG_UPNPAV_AVTRNSPORT_PLAY @"Play"

/****************************************
* Constants (Content Directory)
****************************************/

#define CG_UPNPAV_CONTENTDIRECTORY_SERVICE_TYPE @"urn:schemas-upnp-org:service:ContentDirectory:1"

#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE @"Browse"
	
#define CG_UPNPAV_CONTENTDIRECTORY_SEARCH @"Search"

#define CG_UPNPAV_CONTENTDIRECTORY_GET_SEARCH_CAPABILITIES @"GetSearchCapabilities"
#define CG_UPNPAV_CONTENTDIRECTORY_SEARCH_CAPS @"SearchCaps"
	
#define CG_UPNPAV_CONTENTDIRECTORY_GET_SORT_CAPABILITIES @"GetSortCapabilities"
#define CG_UPNPAV_CONTENTDIRECTORY_SORT_CAPS @"SortCaps"
	
#define CG_UPNPAV_CONTENTDIRECTORY_GET_SYSTEM_UPDATE_ID @"GetSystemUpdateID"
#define CG_UPNPAV_CONTENTDIRECTORY_ID @"Id"

#define CG_UPNPAV_CONTENTDIRECTORY_SYSTEM_UPDATE_ID @"SystemUpdateID"
#define CG_UPNPAV_CONTENTDIRECTORY_SEARCH_CAPABILITIES @"SearchCapabilities"
#define CG_UPNPAV_CONTENTDIRECTORY_SORT_CAPABILITIES @"SortCapabilities"
	
#define CG_UPNPAV_CONTENTDIRECTORY_CONTENT_EXPORT_URI @"/ExportContent"
#define CG_UPNPAV_CONTENTDIRECTORY_CONTENT_IMPORT_URI @"/ImportContent"
#define CG_UPNPAV_CONTENTDIRECTORY_CONTENT_ID @"id"

#define CG_UPNPAV_CONTENTDIRECTORY_DEFAULT_SYSTEMUPDATEID_INTERVAL 2000
#define CG_UPNPAV_CONTENTDIRECTORY_DEFAULT_CONTENTUPDATE_INTERVAL 60000

#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE_OBJECT_ID @"ObjectID"
#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE_BROWSE_FLAG @"BrowseFlag"
#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE_FILTER @"Filter"
#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE_STARTING_INDEX @"StartingIndex"
#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE_REQUESTED_COUNT @"RequestedCount"
#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE_SORT_CRITERIA @"SortCriteria"
	
#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE_BROWSE_METADATA @"BrowseMetadata"
#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE_BROWSE_DIRECT_CHILDREN @"BrowseDirectChildren"

#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE_RESULT @"Result"
#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE_NUMBER_RETURNED @"NumberReturned"
#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE_TOTAL_MACHES @"TotalMatches"
#define CG_UPNPAV_CONTENTDIRECTORY_BROWSE_UPDATE_ID @"UpdateID"

/****************************************
* Constants (Connection Manager)
****************************************/

#define CG_UPNPAV_CONNECTIONMANAGER_SERVICE_TYPE @"urn:schemas-upnp-org:service:ConnectionManager:1"

#define CG_UPNPAV_CONNECTIONMANAGER_HTTP_GET @"http-get"
	
#define CG_UPNPAV_CONNECTIONMANAGER_GET_PROTOCOL_INFO @"GetProtocolInfo"
#define CG_UPNPAV_CONNECTIONMANAGER_SOURCE @"Source"
#define CG_UPNPAV_CONNECTIONMANAGER_SINK @"Sink"

#define CG_UPNPAV_CONNECTIONMANAGER_PREPARE_FOR_CONNECTION @"PrepareForConnection"
#define CG_UPNPAV_CONNECTIONMANAGER_REMOTE_PROTOCOL_INFO @"RemoteProtocolInfo"
#define CG_UPNPAV_CONNECTIONMANAGER_PEER_CONNECTION_MANAGER @"PeerConnectionManager"
#define CG_UPNPAV_CONNECTIONMANAGER_PEER_CONNECTION_ID @"PeerConnectionID"
#define CG_UPNPAV_CONNECTIONMANAGER_DIRECTION @"Direction"
#define CG_UPNPAV_CONNECTIONMANAGER_CONNECTION_ID @"ConnectionID"
#define CG_UPNPAV_CONNECTIONMANAGER_AV_TRNSPORT_ID @"AVTransportID"
#define CG_UPNPAV_CONNECTIONMANAGER_RCS_ID @"RcsID"
	
#define CG_UPNPAV_CONNECTIONMANAGER_CONNECTION_COMPLETE @"ConnectionComplete"

#define CG_UPNPAV_CONNECTIONMANAGER_GET_CURRENT_CONNECTION_IDS @"GetCurrentConnectionIDs"
#define CG_UPNPAV_CONNECTIONMANAGER_CONNECTION_IDS @"ConnectionIDs"

#define CG_UPNPAV_CONNECTIONMANAGER_GET_CURRENT_CONNECTION_INFO @"GetCurrentConnectionInfo"
#define CG_UPNPAV_CONNECTIONMANAGER_PROTOCOL_INFO @"ProtocolInfo"
#define CG_UPNPAV_CONNECTIONMANAGER_STATUS @"Status"
#define CG_UPNPAV_CONNECTIONMANAGER_INPUT @"Input"
#define CG_UPNPAV_CONNECTIONMANAGER_OUTPUT @"Output"
#define CG_UPNPAV_CONNECTIONMANAGER_OK @"OK"

#define CG_UPNPAV_OBJECT_ID @"id"
#define CG_UPNPAV_OBJECT_PARENTID @"parentID"
#define CG_UPNPAV_OBJECT_CHILDCOUNT @"childCount"
#define CG_UPNPAV_OBJECT_RESTRICTED @"restricted"
#define CG_UPNPAV_OBJECT_TITLE @"dc:title"
#define CG_UPNPAV_OBJECT_DATE @"dc:date"
#define CG_UPNPAV_OBJECT_UPNPCLASS @"upnp:class"
#define CG_UPNPAV_OBJECT_ALBUMARTURI @"upnp:albumArtURI"

#define CG_UPNPAV_OBJECT_ROOT_ID @"0"

#define CG_UPNPAV_MIMETYPE_JPEG @"image/jpeg"
#define CG_UPNPAV_MIMETYPE_MPEG @"video/mpeg"
#define CG_UPNPAV_MIMETYPE_MP3 @"audio/mpeg"

#define CG_UPNPAV_UPNPCLASS_PHOTO @"object.item.imageItem.photo"
#define CG_UPNPAV_UPNPCLASS_MOVIE @"object.item.videoItem.movie"
#define CG_UPNPAV_UPNPCLASS_MUSIC @"object.item.audioItem.musicTrack"

#define CG_UPNPAV_DLNAPN_MAXLEN 128
	
#define CG_UPNPAV_DLNAPN_JPEG_SM @"JPEG_SM"
#define CG_UPNPAV_DLNAPN_JPEG_MED @"JPEG_MED"
#define CG_UPNPAV_DLNAPN_JPEG_LRG @"JPEG_LRG"
#define CG_UPNPAV_DLNAPN_JPEG_TN @"JPEG_TN"
#define CG_UPNPAV_DLNAPN_JPEG_SM_ICO @"JPEG_SM_ICO"
#define CG_UPNPAV_DLNAPN_JPEG_LRG_ICO @"JPEG_LRG_ICO"
	
#define CG_UPNPAV_DLNAPN_MPEG_PS_NTSC @"MPEG_PS_NTSC"
#define CG_UPNPAV_DLNAPN_MP3 @"MP3"

#define CG_UPNPAV_RESOURCE_NAME @"res"
#define CG_UPNPAV_RESOURCE_PROTOCOLINFO @"protocolInfo"
#define CG_UPNPAV_RESOURCE_PROTOCOLINFO_SIZE @"size"
#define CG_UPNPAV_RESOURCE_DLNAORG_PN @"DLNA.ORG_PN"
#define CG_UPNPAV_RESOURCE_DLNAORG_OP @"DLNA.ORG_OP"
#define CG_UPNPAV_RESOURCE_DLNAORG_FLAGS @"DLNA.ORG_FLAGS"
