@startuml
mUpnpControlPoint *-- mUpnpDevice
mUpnpDevice *-- mUpnpIcon
mUpnpDevice *-- mUpnpService
mUpnpService *-- mUpnpAction
mUpnpAction *-- mUpnpArgument
mUpnpService *-- mUpnpStateVariable
@enduml
